[package]
name = "passgen"
version = "1.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clipboard = "0.5.0"
dirs = "3.0.2"
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
clap = { version = "4.4.18", features = ["derive", "cargo"] }
